const Slot = [
    {
        id: 1,
        slot: '05:00am to 06:30am',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 2,
        slot: '06:30am to 08:00am',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 3,
        slot: '08:00am to 09:30am',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 4,
        slot: '09:30am to 11:00am',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 5,
        slot: '11:00am to 12:30pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 6,
        slot: '12:30pm to 02:00pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 7,
        slot: '02:00pm to 03:30pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 8,
        slot: '03:30pm to 05:00pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 9,
        slot: '05:00pm to 06:30pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 10,
        slot: '06:30pm to 08:00pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 11,
        slot: '08:00pm to 09:30pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 12,
        slot: '09:30pm to 11:00pm',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 13,
        slot: '11:00pm to 12:30am',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    },
    {
        id: 14,
        slot: '12:30am to 02:00am',
        name: 'Minhaz',
        contact: '+8801328501655',
        location: 'Jatrabari',
        advance: '500',
        advanceReceiver: 'Sazzad',
        total: '2500',
        dueReceiver: 'Maruf',
        bookingPerson: 'Minhaz',
    }
]

export default Slot