export const PERMISSIONS = {
  VIEW_OWN_BOOKINGS: "VIEW_OWN_BOOKINGS",
  VIEW_ALL_BOOKINGS: "VIEW_ALL_BOOKINGS",
 COMPLETED_BOOKING: "COMPLETED_BOOKING",
  CONFIRM_BOOKING: "CONFIRM_BOOKING",
  MANAGE_USERS: "MANAGE_USERS",
  CANCEL_BOOKING: "CANCEL_BOOKING", 
};