export const PERMISSIONS = {
  VIEW_OWN_BOOKINGS: "VIEW_OWN_BOOKINGS",
  VIEW_ALL_BOOKINGS: "VIEW_ALL_BOOKINGS",
  UPDATE_BOOKING: "UPDATE_BOOKING",
  APPROVE_BOOKING: "APPROVE_BOOKING",
  MANAGE_USERS: "MANAGE_USERS",
  CANCEL_BOOKING: "CANCEL_BOOKING", 
};