import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  USER: [PERMISSIONS.VIEW_OWN_BOOKINGS], 

  SUPER_ADMIN: [], 

  GENERAL_ADMIN: [
    PERMISSIONS.VIEW_ALL_BOOKINGS,
    PERMISSIONS.UPDATE_BOOKING,
  ],

  MODERATOR: [
    PERMISSIONS.VIEW_ALL_BOOKINGS,
    PERMISSIONS.APPROVE_BOOKING,
  ],

  INSPECT_ADMIN: [
    PERMISSIONS.VIEW_ALL_BOOKINGS,
  ],
};