import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  USER: [PERMISSIONS.VIEW_OWN_BOOKINGS],

  SUPER_ADMIN: [],

  GENERAL_ADMIN: [
    PERMISSIONS.VIEW_ALL_BOOKINGS,
    PERMISSIONS.CONFIRM_BOOKING,
    PERMISSIONS.COMPLETED_BOOKING,
    PERMISSIONS.CANCEL_BOOKING,
  ],

  MODERATOR: [PERMISSIONS.VIEW_ALL_BOOKINGS, PERMISSIONS.CONFIRM_BOOKING ,
    PERMISSIONS.COMPLETED_BOOKING

  ],

  INSPECT_ADMIN: [PERMISSIONS.VIEW_ALL_BOOKINGS],
};
